build(ci): override env vars before each relevamt workflow

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -8,7 +8,7 @@ app:
   - RELEASE_SCG: false
   - RELEASE_LOANS: false
   - RELEASE_TYPE: qa
-  - BINARY_PATH: ".build/Products/SmartInvesting/Smart Investing.ipa"
+  - BINARY_PATH: .build/Products/SmartInvesting/Smart Investing.ipa
   - COCOA_REPO: sc-cocoapodspec-internal
   - COCOA_REPO_URL: https://github.com/smallcase/cocoapodspec-internal.git
   - SCG_PODSPEC: smallcase_gateway/internal/SCGateway-ci.podspec.json
@@ -56,6 +56,8 @@ workflows:
       opts:
         is_expand: false
   release-sdks:
+    before_run:
+    - z-override-envs
     envs:
     - SCG_XC_FRAMEWORK_PATH: .build/Products/SCGateway.xcframework
     - LOANS_XC_FRAMEWORK_PATH: .build/Products/Loans.xcframework
@@ -104,6 +106,9 @@ workflows:
               $SCLI_PATH cocoapodDeploy --cocoapodDeploy.framework "$LOANS_XC_FRAMEWORK_PATH" --cocoapodDeploy.podspec "$loans_podspec" --cocoapodDeploy.repo "$repo" --cocoapodDeploy.repoUrl "$repo_url"
             fi
   x-ci-setup:
+    after_run:
+    - z-override-envs
+    - z-install-scli
     steps:
     - set-git-credentials@1:
         run_if: .IsCI
@@ -130,45 +135,7 @@ workflows:
         run_if: .IsCI
         inputs:
         - is_cache_disabled: "true"
-    - script@1:
-        title: Install SCLI
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            set -e
-            set -o pipefail
-            set -x
-
-            curl -H "Authorization: token $GITHUB_ACCESS_TOKEN" -s https://raw.githubusercontent.com/smallcase/scli/master/install.sh | bash -s -- $SCLI_VERSION $GITHUB_ACCESS_TOKEN
     - manage-ios-code-signing@2: {}
-    - script@1:
-        title: Override Env variables
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-
-            # Fail if any commands fail
-            set -e
-            # Make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
-            set -o pipefail
-            # Debug log
-            set -x
-
-            # Loop through all environment variables
-            for var in $(env | grep -o '^OVERRIDE_[^=]*'); do
-              # Extract the base variable name by removing the 'OVERRIDE_' prefix
-              base_var=${var#OVERRIDE_}
-
-              # Get the value of the OVERRIDE_ variable
-              override_value=$(eval echo \$$var)
-
-              # Check if the base variable exists
-              if [[ -n $(eval echo \$$base_var) ]]; then
-                echo "Overriding $base_var with $override_value"
-                envman add --key "$base_var" --value "$override_value"
-              fi
-            done
-
   z-assemble:
     steps:
     - script@1:
@@ -187,6 +154,8 @@ workflows:
 
             sh BuildScripts/assemble.sh
   z-firebase-deploy:
+    before_run:
+    - z-override-envs
     steps:
     - script@1:
         title: Install Firebase CLI
@@ -266,3 +235,44 @@ workflows:
             firebase_changelog=$($SCLI_PATH changelog --format "firebase" --dirs "$scope")
 
             firebase appdistribution:distribute "$BINARY_PATH" --app "$FIREBASE_APP_ID" --release-notes "$firebase_changelog" --groups "smallcase"
+  z-install-scli:
+    steps:
+    - script@1:
+        title: Install SCLI
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            set -o pipefail
+            set -x
+
+            curl -H "Authorization: token $GITHUB_ACCESS_TOKEN" -s https://raw.githubusercontent.com/smallcase/scli/master/install.sh | bash -s -- $SCLI_VERSION $GITHUB_ACCESS_TOKEN
+  z-override-envs:
+    steps:
+    - script@1:
+        title: Override Env variables
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+
+            # Fail if any commands fail
+            set -e
+            # Make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # Debug log
+            set -x
+
+            # Loop through all environment variables
+            for var in $(env | grep -o '^OVERRIDE_[^=]*'); do
+              # Extract the base variable name by removing the 'OVERRIDE_' prefix
+              base_var=${var#OVERRIDE_}
+
+              # Get the value of the OVERRIDE_ variable
+              override_value=$(eval echo \$$var)
+
+              # Check if the base variable exists
+              if [[ -n $(eval echo \$$base_var) ]]; then
+                echo "Overriding $base_var with $override_value"
+                envman add --key "$base_var" --value "$override_value"
+              fi
+            done
